### ISSUE TITLE
In what code language have u wrote it?>

### ISSUE THREAD

**Issue by Natan515** [maybepiffpuffas/kahoot-flooder#6]
And I would really appreciate it if you would put it open source, I mean before it become.exe so I can edit it too.

**Comment by maybepiffpuffas** [comment]
Hi, the code I wrote here doesn't seem to work now, because this was written about 9 months ago, I used node.js with the kahoot.js-updated library they have some examples and it's pretty easy to use.

**Comment by Natan515** [comment]
Thanks, I know it works for me. I'm trying to make the same thing too (;

**Comment by maybepiffpuffas** [comment]
> Thanks, I know it works for me. I'm trying to make the same thing too (;

Good luck :)
