### ISSUE TITLE
Is my IP address shown?

### ISSUE THREAD

**Issue by liferific** [maybepiffpuffas/kahoot-flooder#7]
When I activate the Kahoot bot, is my IP address shown to Kahoot or does it use the bot’s IP address?

**Comment by maybepiffpuffas** [comment]
> When I activate the Kahoot bot, is my IP address shown to Kahoot or does it use the bot’s IP address?

Yes, but you can use a free vpn service to hide your ip - [https://protonvpn.com/pricing](https://protonvpn.com/pricing)

**Comment by liferific** [comment]
What if my teacher reports me to Kahoot? Will they block me?

**Comment by maybepiffpuffas** [comment]
> What if my teacher reports me to Kahoot? Will they block me?
Your teacher can't see your ip.

**Comment by liferific** [comment]
I mean if they report me to Kahoot? Will Kahoot block me or send my IP to the teacher?

**Comment by maybepiffpuffas** [comment]
> I mean if they report me to Kahoot? Will Kahoot block me or send my IP to the teacher?

Nothing will happen, and if you are scared download a vpn (protonvpn.com)

**Comment by liferific** [comment]
Can you please completely permanently delete this issue? Thank you.
